import React, { useState, useEffect } from 'react';
import {
  Dialog, DialogContent, Box, Typography, Button, IconButton,
  TextField, CircularProgress, Divider, Paper, Grid,
  Tooltip, Collapse
} from '@mui/material';
import {
  Close, Security, CheckCircle, CreditCard,
  FlashOn, Lock, ContentCopy, Check,
  Tune, ArrowForward, ShieldOutlined, ReceiptLong
} from '@mui/icons-material';
import { feeAPI } from '../../services/api';
import { toast } from 'react-toastify';

// Helper to dynamically ensure official Razorpay Checkout SDK is loaded
const loadRazorpayScript = () => {
  return new Promise((resolve) => {
    if (window.Razorpay) {
      resolve(true);
      return;
    }
    const script = document.createElement('script');
    script.src = 'https://checkout.razorpay.com/v1/checkout.js';
    script.async = true;
    script.onload = () => resolve(true);
    script.onerror = () => resolve(false);
    document.body.appendChild(script);
  });
};

export default function RazorpayCheckoutModal({
  open,
  onClose,
  fee,
  student,
  onSuccess
}) {
  const [loading, setLoading] = useState(false);
  const [verifying, setVerifying] = useState(false);
  const [paymentSuccess, setPaymentSuccess] = useState(false);
  const [latestTxn, setLatestTxn] = useState(null);
  const [copiedField, setCopiedField] = useState(null);
  const [showConfig, setShowConfig] = useState(false);

  // Gateway credentials state
  const [keyConfig, setKeyConfig] = useState({
    keyId: 'rzp_test_Th4Zu9hPWOhfeY',
    testMode: true,
    gateway: 'Razorpay'
  });
  const [customKeyId, setCustomKeyId] = useState('rzp_test_Th4Zu9hPWOhfeY');
  const [customKeySecret, setCustomKeySecret] = useState('SbOd4QyJx1Kh2pjEIe3NPNN6');
  const [updatingKeys, setUpdatingKeys] = useState(false);

  // Fetch current Razorpay gateway configuration
  useEffect(() => {
    if (open) {
      feeAPI.getConfig()
        .then(res => {
          if (res.data?.data) {
            setKeyConfig(res.data.data);
            setCustomKeyId(res.data.data.keyId || 'rzp_test_Th4Zu9hPWOhfeY');
          }
        })
        .catch(() => {});
      setPaymentSuccess(false);
      setLatestTxn(null);
      setShowConfig(false);
    }
  }, [open]);

  if (!fee) return null;

  const amountRupees = Number(fee.amount || 0);

  const handleCopy = (text, fieldName) => {
    navigator.clipboard.writeText(text);
    setCopiedField(fieldName);
    toast.info(`Copied ${fieldName} to clipboard`);
    setTimeout(() => setCopiedField(null), 2500);
  };

  const handleSaveApiKeys = async () => {
    if (!customKeyId.trim()) {
      toast.warning('Please enter a valid Razorpay Key ID');
      return;
    }
    setUpdatingKeys(true);
    try {
      const res = await feeAPI.updateConfig({
        keyId: customKeyId.trim(),
        keySecret: customKeySecret.trim()
      });
      if (res.data?.data) {
        setKeyConfig(res.data.data);
      }
      toast.success('Razorpay API keys updated successfully');
      setShowConfig(false);
    } catch {
      toast.error('Failed to update Razorpay API keys');
    } finally {
      setUpdatingKeys(false);
    }
  };

  // 1. Launch Authentic Official Razorpay Checkout Modal (SDK)
  const launchOfficialRazorpay = async () => {
    setLoading(true);

    // Verify SDK availability
    const scriptLoaded = await loadRazorpayScript();
    if (!scriptLoaded || !window.Razorpay) {
      toast.warning('Razorpay Checkout SDK unreachable. Falling back to sandbox simulator.');
      launchSandboxSimulation();
      setLoading(false);
      return;
    }

    try {
      // 1. Generate Order on backend
      const orderRes = await feeAPI.createPaymentOrder(fee.id);
      const orderData = orderRes.data?.data || {};

      const currentKey = keyConfig.keyId || orderData.keyId || 'rzp_test_Th4Zu9hPWOhfeY';

      // 2. Build standard Razorpay Checkout options
      const options = {
        key: currentKey,
        amount: orderData.amount || (amountRupees * 100),
        currency: orderData.currency || 'INR',
        name: 'CampusIQ University',
        description: `${fee.feeType} — Invoice #${fee.id}`,
        image: 'https://cdn-icons-png.flaticon.com/512/3135/3135715.png',
        // Real order ID generated by Razorpay
        order_id: (orderData.orderId && !orderData.orderId.startsWith('order_test_')) ? orderData.orderId : undefined,
        handler: async function (response) {
          setLoading(false);
          setVerifying(true);
          try {
            const verifyRes = await feeAPI.verifyPayment({
              feeId: fee.id,
              razorpayOrderId: response.razorpay_order_id || orderData.orderId || `order_${Date.now()}`,
              razorpayPaymentId: response.razorpay_payment_id,
              razorpaySignature: response.razorpay_signature || `sig_${Date.now()}`
            });

            if (verifyRes.data?.success) {
              setPaymentSuccess(true);
              setLatestTxn({
                paymentId: response.razorpay_payment_id,
                orderId: response.razorpay_order_id || orderData.orderId,
                amount: amountRupees,
                feeType: fee.feeType,
                timestamp: new Date().toLocaleString()
              });
              toast.success('Payment verified & settled successfully');
              if (onSuccess) onSuccess();
            } else {
              toast.error('Cryptographic signature verification failed');
            }
          } catch (err) {
            toast.error(err.response?.data?.message || 'Payment settlement error');
          } finally {
            setVerifying(false);
          }
        },
        prefill: {
          name: student?.name || 'Student Account',
          email: student?.email || 'student@campusiq.edu',
          contact: student?.phoneNumber || student?.phone || '9876543210'
        },
        notes: {
          feeId: String(fee.id),
          feeType: fee.feeType,
          studentRoll: student?.enrollmentNumber || '24CS001',
          institution: 'CampusIQ University Portal'
        },
        theme: {
          color: '#0f172a'
        },
        modal: {
          ondismiss: function () {
            setLoading(false);
          }
        }
      };

      const rzpInstance = new window.Razorpay(options);

      rzpInstance.on('payment.failed', function (failureResp) {
        setLoading(false);
        toast.error(`Transaction declined: ${failureResp.error?.description || 'Gateway rejection'}`);
      });

      rzpInstance.open();
    } catch (err) {
      toast.error(err.response?.data?.message || 'Could not initiate payment session');
    } finally {
      setLoading(false);
    }
  };

  // 2. Direct 1-Click Fast Sandbox Simulation (Alternative test mode path)
  const launchSandboxSimulation = async () => {
    setLoading(true);
    setVerifying(true);
    try {
      const orderRes = await feeAPI.createPaymentOrder(fee.id);
      const order = orderRes.data?.data || {};
      const orderId = order.orderId || `order_test_${Math.random().toString(36).substring(2, 10)}`;

      await new Promise(r => setTimeout(r, 900));

      const paymentId = `pay_test_${Math.random().toString(36).substring(2, 10)}${Date.now().toString().slice(-4)}`;
      const signature = `test_sig_${Math.random().toString(36).substring(2, 14)}`;

      const verifyRes = await feeAPI.verifyPayment({
        feeId: fee.id,
        razorpayOrderId: orderId,
        razorpayPaymentId: paymentId,
        razorpaySignature: signature
      });

      if (verifyRes.data?.success) {
        setPaymentSuccess(true);
        setLatestTxn({
          paymentId,
          orderId,
          amount: amountRupees,
          feeType: fee.feeType,
          timestamp: new Date().toLocaleString()
        });
        toast.success('Payment verified & settled');
        if (onSuccess) onSuccess();
      } else {
        throw new Error('Verification failed');
      }
    } catch (err) {
      toast.error(err.response?.data?.message || 'Settlement failed');
    } finally {
      setLoading(false);
      setVerifying(false);
    }
  };

  const handleClose = () => {
    if (loading || verifying) return;
    setPaymentSuccess(false);
    setLatestTxn(null);
    onClose();
  };

  return (
    <Dialog
      open={open}
      onClose={handleClose}
      maxWidth="sm"
      fullWidth
      PaperProps={{
        sx: {
          borderRadius: '16px',
          overflow: 'hidden',
          bgcolor: '#ffffff',
          boxShadow: '0 25px 50px -12px rgba(15, 23, 42, 0.35)',
          border: '1px solid #e2e8f0'
        }
      }}
    >
      {/* Enterprise FinTech Header */}
      <Box
        sx={{
          bgcolor: '#0a192f',
          color: '#ffffff',
          px: 3.5,
          py: 2.2,
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          borderBottom: '1px solid rgba(255, 255, 255, 0.08)'
        }}
      >
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5 }}>
          {/* Razorpay Brand Glyph */}
          <Box
            sx={{
              display: 'flex',
              alignItems: 'center',
              gap: 1,
              bgcolor: 'rgba(255, 255, 255, 0.07)',
              px: 1.5,
              py: 0.5,
              borderRadius: '8px',
              border: '1px solid rgba(255, 255, 255, 0.12)'
            }}
          >
            <Box
              component="span"
              sx={{
                width: 18,
                height: 18,
                bgcolor: '#0284c7',
                borderRadius: '4px',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontSize: 11,
                fontWeight: 900,
                color: '#ffffff'
              }}
            >
              R
            </Box>
            <Typography
              variant="subtitle2"
              sx={{
                fontWeight: 800,
                letterSpacing: 0.4,
                fontSize: 13,
                color: '#f8fafc'
              }}
            >
              Razorpay
            </Typography>
            <Typography
              variant="caption"
              sx={{
                fontSize: 9,
                fontWeight: 800,
                color: '#38bdf8',
                bgcolor: 'rgba(56, 189, 248, 0.15)',
                px: 0.8,
                py: 0.2,
                borderRadius: '4px',
                letterSpacing: 0.5
              }}
            >
              TEST MODE
            </Typography>
          </Box>
        </Box>

        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5 }}>
          <Box
            sx={{
              display: 'flex',
              alignItems: 'center',
              gap: 0.6,
              color: '#94a3b8',
              fontSize: 11,
              fontWeight: 600
            }}
          >
            <Lock sx={{ fontSize: 13, color: '#38bdf8' }} />
            <span>256-Bit Encrypted</span>
          </Box>
          <IconButton
            onClick={handleClose}
            size="small"
            sx={{
              color: '#64748b',
              bgcolor: 'rgba(255, 255, 255, 0.05)',
              '&:hover': { color: '#ffffff', bgcolor: 'rgba(255, 255, 255, 0.12)' }
            }}
          >
            <Close sx={{ fontSize: 18 }} />
          </IconButton>
        </Box>
      </Box>

      <DialogContent sx={{ p: 0 }}>
        {verifying ? (
          /* Sleek Verifying State */
          <Box sx={{ p: 6, textAlign: 'center', bgcolor: '#fafafa' }}>
            <Box sx={{ position: 'relative', display: 'inline-flex', mb: 3 }}>
              <CircularProgress size={64} thickness={4} sx={{ color: '#0284c7' }} />
              <Box
                sx={{
                  top: 0,
                  left: 0,
                  bottom: 0,
                  right: 0,
                  position: 'absolute',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center'
                }}
              >
                <ShieldOutlined sx={{ fontSize: 26, color: '#0284c7' }} />
              </Box>
            </Box>
            <Typography variant="h6" fontWeight={800} color="#0f172a" mb={0.5}>
              Verifying Transaction
            </Typography>
            <Typography variant="body2" color="#64748b" mb={2}>
              Validating HMAC cryptographic token with ledger for ₹{amountRupees.toLocaleString('en-IN')}.00...
            </Typography>
            <Typography variant="caption" fontFamily="monospace" color="#94a3b8">
              Order: {fee.razorpayOrderId || 'Generating reference...'}
            </Typography>
          </Box>
        ) : paymentSuccess ? (
          /* Sleek Success State */
          <Box sx={{ p: 4.5, textAlign: 'center' }}>
            <Box
              sx={{
                width: 60,
                height: 60,
                borderRadius: '50%',
                bgcolor: '#ecfdf5',
                border: '1.5px solid #a7f3d0',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                mx: 'auto',
                mb: 2.5
              }}
            >
              <CheckCircle sx={{ fontSize: 36, color: '#059669' }} />
            </Box>

            <Typography variant="h5" fontWeight={800} color="#0f172a" mb={0.5}>
              Payment Successful
            </Typography>
            <Typography variant="body2" color="#64748b" mb={3}>
              The institutional invoice has been paid and settled on the student ledger.
            </Typography>

            <Paper
              elevation={0}
              sx={{
                p: 2.5,
                bgcolor: '#f8fafc',
                border: '1px solid #e2e8f0',
                borderRadius: '12px',
                textAlign: 'left',
                mb: 3
              }}
            >
              <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1.5 }}>
                <Typography variant="caption" color="#64748b" fontWeight={600}>Total Amount Settled</Typography>
                <Typography variant="body2" fontWeight={800} color="#0f172a">
                  ₹{amountRupees.toLocaleString('en-IN')}.00
                </Typography>
              </Box>
              <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1.5 }}>
                <Typography variant="caption" color="#64748b" fontWeight={600}>Fee Classification</Typography>
                <Typography variant="body2" fontWeight={700} color="#0f172a">
                  {fee.feeType}
                </Typography>
              </Box>
              <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1.5 }}>
                <Typography variant="caption" color="#64748b" fontWeight={600}>Razorpay Payment ID</Typography>
                <Typography variant="caption" fontFamily="monospace" fontWeight={700} color="#0284c7">
                  {latestTxn?.paymentId}
                </Typography>
              </Box>
              <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1.5 }}>
                <Typography variant="caption" color="#64748b" fontWeight={600}>Razorpay Order ID</Typography>
                <Typography variant="caption" fontFamily="monospace" fontWeight={700} color="#64748b">
                  {latestTxn?.orderId}
                </Typography>
              </Box>
              <Divider sx={{ my: 1.5 }} />
              <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <Typography variant="caption" color="#64748b" fontWeight={600}>Verification Status</Typography>
                <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.5, color: '#059669' }}>
                  <Check sx={{ fontSize: 15, fontWeight: 900 }} />
                  <Typography variant="caption" fontWeight={800} color="#059669">
                    Ledger Settled
                  </Typography>
                </Box>
              </Box>
            </Paper>

            <Button
              variant="contained"
              fullWidth
              onClick={handleClose}
              sx={{
                bgcolor: '#0f172a',
                '&:hover': { bgcolor: '#1e293b' },
                py: 1.3,
                borderRadius: '10px',
                fontWeight: 700,
                textTransform: 'none',
                fontSize: 14
              }}
            >
              Done & View Verified Receipt
            </Button>
          </Box>
        ) : (
          /* Institutional Invoice & Payment Launcher */
          <Box sx={{ p: 3.5 }}>
            {/* Invoice Meta Bar */}
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', mb: 2.5 }}>
              <Box>
                <Typography variant="caption" sx={{ color: '#64748b', fontWeight: 700, letterSpacing: 0.6, textTransform: 'uppercase', fontSize: 10 }}>
                  Institutional Fee Assessment
                </Typography>
                <Typography variant="h6" fontWeight={800} color="#0f172a" sx={{ lineHeight: 1.2, mt: 0.3 }}>
                  {fee.feeType}
                </Typography>
                <Typography variant="body2" color="#64748b" sx={{ fontSize: 12, mt: 0.3 }}>
                  Student: <strong>{student?.name || 'Aarav Varma'}</strong> ({student?.enrollmentNumber || '24CS001'})
                </Typography>
              </Box>

              <Box sx={{ textAlign: 'right' }}>
                <Typography variant="caption" sx={{ color: '#64748b', fontWeight: 700, letterSpacing: 0.6, textTransform: 'uppercase', fontSize: 10 }}>
                  Total Net Payable
                </Typography>
                <Typography
                  variant="h4"
                  fontWeight={900}
                  sx={{
                    color: '#0f172a',
                    fontFamily: 'Roboto, -apple-system, sans-serif',
                    letterSpacing: -0.5
                  }}
                >
                  ₹{amountRupees.toLocaleString('en-IN')}.00
                </Typography>
              </Box>
            </Box>

            {/* Itemized Breakdown Card */}
            <Paper
              elevation={0}
              sx={{
                p: 2.2,
                mb: 3,
                bgcolor: '#f8fafc',
                border: '1px solid #e2e8f0',
                borderRadius: '12px'
              }}
            >
              <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1 }}>
                <Typography variant="body2" color="#475569">Tuition Assessment Base</Typography>
                <Typography variant="body2" fontWeight={700} color="#0f172a">
                  ₹{amountRupees.toLocaleString('en-IN')}.00
                </Typography>
              </Box>
              <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1 }}>
                <Typography variant="body2" color="#475569">Gateway Convenience Charge</Typography>
                <Typography variant="body2" fontWeight={700} color="#059669">
                  ₹0.00 (Waived)
                </Typography>
              </Box>
            </Paper>

            {/* Primary Action Button */}
            <Button
              variant="contained"
              fullWidth
              size="large"
              onClick={launchOfficialRazorpay}
              disabled={loading}
              endIcon={!loading && <ArrowForward sx={{ fontSize: 18 }} />}
              sx={{
                bgcolor: '#0f172a',
                '&:hover': { bgcolor: '#1e293b' },
                py: 1.5,
                borderRadius: '10px',
                textTransform: 'none',
                fontWeight: 700,
                fontSize: 15,
                boxShadow: '0 10px 15px -3px rgba(15, 23, 42, 0.2)'
              }}
            >
              {loading ? (
                <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                  <CircularProgress size={18} sx={{ color: '#fff' }} />
                  <span>Connecting Razorpay Gateway...</span>
                </Box>
              ) : (
                `Proceed to Pay ₹${amountRupees.toLocaleString('en-IN')}.00`
              )}
            </Button>

            {/* Minimalist Test Sandbox Guide (Zero Financial Risk) */}
            <Box
              sx={{
                mt: 2.5,
                p: 2,
                borderRadius: '10px',
                border: '1px solid #e2e8f0',
                bgcolor: '#fafafa'
              }}
            >
              <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 1.2 }}>
                <Typography variant="caption" fontWeight={700} color="#475569" sx={{ textTransform: 'uppercase', letterSpacing: 0.5, fontSize: 10 }}>
                  Test Credentials (Click to copy):
                </Typography>
                <Typography variant="caption" color="#94a3b8" sx={{ fontSize: 10 }}>
                  Simulated sandbox • No charges
                </Typography>
              </Box>

              <Grid container spacing={1}>
                <Grid item xs={6}>
                  <Box
                    onClick={() => handleCopy('4111111111111111', 'Card Number')}
                    sx={{
                      p: 1,
                      bgcolor: '#ffffff',
                      borderRadius: '6px',
                      border: '1px solid #e2e8f0',
                      cursor: 'pointer',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'space-between',
                      transition: 'all 0.15s ease',
                      '&:hover': { borderColor: '#0f172a', bgcolor: '#f8fafc' }
                    }}
                  >
                    <Box>
                      <Typography variant="caption" color="#64748b" display="block" sx={{ fontSize: 9, fontWeight: 600 }}>
                        TEST CARD
                      </Typography>
                      <Typography variant="caption" fontFamily="monospace" fontWeight={700} color="#0f172a">
                        4111 1111 1111 1111
                      </Typography>
                    </Box>
                    {copiedField === 'Card Number' ? (
                      <Check sx={{ fontSize: 14, color: '#059669' }} />
                    ) : (
                      <ContentCopy sx={{ fontSize: 13, color: '#94a3b8' }} />
                    )}
                  </Box>
                </Grid>

                <Grid item xs={6}>
                  <Box
                    onClick={() => handleCopy('success@razorpay', 'UPI ID')}
                    sx={{
                      p: 1,
                      bgcolor: '#ffffff',
                      borderRadius: '6px',
                      border: '1px solid #e2e8f0',
                      cursor: 'pointer',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'space-between',
                      transition: 'all 0.15s ease',
                      '&:hover': { borderColor: '#0f172a', bgcolor: '#f8fafc' }
                    }}
                  >
                    <Box>
                      <Typography variant="caption" color="#64748b" display="block" sx={{ fontSize: 9, fontWeight: 600 }}>
                        TEST UPI
                      </Typography>
                      <Typography variant="caption" fontFamily="monospace" fontWeight={700} color="#0f172a">
                        success@razorpay
                      </Typography>
                    </Box>
                    {copiedField === 'UPI ID' ? (
                      <Check sx={{ fontSize: 14, color: '#059669' }} />
                    ) : (
                      <ContentCopy sx={{ fontSize: 13, color: '#94a3b8' }} />
                    )}
                  </Box>
                </Grid>
              </Grid>

              <Typography variant="caption" color="#94a3b8" sx={{ display: 'block', mt: 1, fontSize: 10 }}>
                Exp: <strong>12/28</strong> • CVV: <strong>123</strong> • OTP: <strong>123456</strong>
              </Typography>
            </Box>
          </Box>
        )}
      </DialogContent>
    </Dialog>
  );
}
